// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEzKwmLG1fQhoccq0L6kq6s-wch-W6uLI',
    appId: '1:73294790038:android:751f14edf77314afe331b7',
    messagingSenderId: '73294790038',
    projectId: 'etherealestate-60c03',
    storageBucket: 'etherealestate-60c03.firebasestorage.app',
  );

  // ─── ANDROID ─────────────────────────────────────────────────────────────

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGYSIpKq7tKo2EkJsxRNzBO4E7XEvLdSw',
    appId: '1:73294790038:ios:ce3d04992de6567fe331b7',
    messagingSenderId: '73294790038',
    projectId: 'etherealestate-60c03',
    storageBucket: 'etherealestate-60c03.firebasestorage.app',
    iosBundleId: 'com.axiom.etherealestate',
  );

  // ─── iOS ─────────────────────────────────────────────────────────────────

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6E7o2hRMIRv-_2wR5aJ9qUI-P0184wSg',
    appId: '1:73294790038:web:f6a442a30b0eae76e331b7',
    messagingSenderId: '73294790038',
    projectId: 'etherealestate-60c03',
    authDomain: 'etherealestate-60c03.firebaseapp.com',
    storageBucket: 'etherealestate-60c03.firebasestorage.app',
    measurementId: 'G-DCTGZKLTCC',
  );

  // ─── Web ─────────────────────────────────────────────────────────────────

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGYSIpKq7tKo2EkJsxRNzBO4E7XEvLdSw',
    appId: '1:73294790038:ios:ce3d04992de6567fe331b7',
    messagingSenderId: '73294790038',
    projectId: 'etherealestate-60c03',
    storageBucket: 'etherealestate-60c03.firebasestorage.app',
    iosBundleId: 'com.axiom.etherealestate',
  );

  // ─── macOS ───────────────────────────────────────────────────────────────

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6E7o2hRMIRv-_2wR5aJ9qUI-P0184wSg',
    appId: '1:73294790038:web:d6865d56958e6df8e331b7',
    messagingSenderId: '73294790038',
    projectId: 'etherealestate-60c03',
    authDomain: 'etherealestate-60c03.firebaseapp.com',
    storageBucket: 'etherealestate-60c03.firebasestorage.app',
    measurementId: 'G-R60MP9W0TB',
  );

  // ─── Windows ─────────────────────────────────────────────────────────────
}